# Site settings
title: Portfolio | Matthew Mazer
email: m@ttmazer.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "localhost" # the base hostname & protocol for your site
twitter_username: retmaze
github_username:  mattmazer
safe: true
timezone: America/New_York
excerpt_separator: ""
highlighter: pygments
include: [.htaccess, robots.txt]
exclude: [Gemfile, README.md]

# Build settings
markdown: kramdown
